[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm install && npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=31536000"
