[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm install && npx tailwindcss -i ./styles.css -o ./dist/styles.css --minify"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=31536000"